language: c
compiler:
  - gcc
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install gcc-4.9
  - sudo apt-get install libstdc++6
  - sudo apt-get install gcc-multilib g++-multilib
  - sudo apt-get install lib32ncurses5-dev
  - sudo apt-get install libx11-dev:i386 libxext-dev:i386 libxrender-dev:i386 libxrandr-dev:i386 libxpm-dev:i386
  - wget https://sourceforge.net/projects/fbc/files/Binaries%20-%20Linux/FreeBASIC-1.05.0-linux-x86_64.tar.gz
  - tar -xvzf FreeBASIC-1.05.0-linux-x86_64.tar.gz
  - cd FreeBASIC-1.05.0-linux-x86_64 && sudo ./install.sh -i && cd ..
  - LD_LIBRARY_PATH=/usr/local/lib64/:$LD_LIBRARY_PATH
  - export LD_LIBRARY_PATH
before_script:
  - chmod +x ./tests/ic17int
script: make && sh ./tests/tests_runner.sh